# Helper script to migrate from Recreate strategy to Canary deployment
# Usage: .\migrate-from-recreate.ps1 -DeploymentName "my-app" -Namespace "default" [-OutputDir "."]
param(
    [Parameter(Mandatory=$true)]
    [string]$DeploymentName,
    [Parameter(Mandatory=$true)]
    [string]$Namespace,
    [string]$OutputDir = "."
)

$ErrorActionPreference = "Stop"

Write-Host "Migrating Deployment '$DeploymentName' from Recreate to Canary setup" -ForegroundColor Cyan

# Export current deployment
$currentYaml = "$OutputDir\current-deployment-backup.yaml"
Write-Host "`n1. Exporting current deployment to: $currentYaml" -ForegroundColor Yellow
kubectl get deployment $DeploymentName -n $Namespace -o yaml | Out-File -FilePath $currentYaml -Encoding utf8
Write-Host "   ✓ Backup saved" -ForegroundColor Green

# Check if it uses Recreate strategy
$deployYaml = kubectl get deployment $DeploymentName -n $Namespace -o yaml
if ($deployYaml -match "type:\s*Recreate") {
    Write-Host "`n⚠️  WARNING: Deployment uses Recreate strategy (causes downtime)" -ForegroundColor Yellow
    Write-Host "   This migration will convert it to canary (no downtime)" -ForegroundColor Gray
} else {
    Write-Host "`n✓ Deployment does not use Recreate strategy" -ForegroundColor Green
}

# Get app labels
$appLabel = (kubectl get deployment $DeploymentName -n $Namespace -o jsonpath='{.spec.selector.matchLabels.app}' 2>$null)
if (-not $appLabel) {
    $appLabel = $DeploymentName
    Write-Host "`n⚠️  No 'app' label found, using deployment name: $appLabel" -ForegroundColor Yellow
} else {
    Write-Host "`n✓ Found app label: $appLabel" -ForegroundColor Green
}

# Generate stable deployment YAML
$stableYaml = @"
# Stable deployment (converted from $DeploymentName)
# Generated by migrate-from-recreate.ps1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
  namespace: $Namespace
  labels:
    app: $appLabel
    version: stable
spec:
  # strategy.type: Recreate removed (defaults to RollingUpdate)
  replicas: $(kubectl get deployment $DeploymentName -n $Namespace -o jsonpath='{.spec.replicas}')
  selector:
    matchLabels:
      app: $appLabel
      version: stable
  template:
    metadata:
      labels:
        app: $appLabel
        version: stable
    spec:
      # TODO: Copy container spec from current deployment
      # Use: kubectl get deployment $DeploymentName -n $Namespace -o jsonpath='{.spec.template.spec}' | yq
      containers:
      - name: app
        image: PLACEHOLDER_IMAGE  # Update this with your image
        # Copy rest of container spec from current deployment
---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  namespace: $Namespace
  labels:
    app: $appLabel
    version: stable
spec:
  selector:
    app: $appLabel
    version: stable
  ports:
  - port: 80
    targetPort: 8080  # Update if needed
    name: http
"@

$stableFile = "$OutputDir\stable-generated.yaml"
$stableYaml | Out-File -FilePath $stableFile -Encoding utf8
Write-Host "`n2. Generated stable deployment template: $stableFile" -ForegroundColor Yellow
Write-Host "   ⚠️  MANUAL STEP REQUIRED:" -ForegroundColor Red
Write-Host "      - Copy container spec from current deployment" -ForegroundColor Gray
Write-Host "      - Update image name" -ForegroundColor Gray
Write-Host "      - Update port numbers if needed" -ForegroundColor Gray

Write-Host "`n3. Next steps:" -ForegroundColor Cyan
Write-Host "   a) Review and update: $stableFile" -ForegroundColor White
Write-Host "   b) Create canary deployment (copy stable, change image to new version)" -ForegroundColor White
Write-Host "   c) Deploy stable: kubectl apply -f $stableFile" -ForegroundColor White
Write-Host "   d) Deploy canary: kubectl apply -f k8s/base/canary.yaml" -ForegroundColor White
Write-Host "   e) Update/create ingresses (see docs/03-Migrate-From-Recreate.md)" -ForegroundColor White

Write-Host "`n✓ Migration preparation complete" -ForegroundColor Green
Write-Host "   Backup saved: $currentYaml" -ForegroundColor Gray
